export const projects = [
	{
		Name: 'QualityHub + InterviewQ',
		Type: 'Team Project',
		Description: '',
		Team: '',
		TechStack1: '',
		TechStack2: '',
		TechStack3: '',
		SiteLink: '',
		PresentationVideo: '',
		MarketingVideo: '',
		CodeRepo1: '',
		CodeRepo2: '',
		CodeRepo3: '',
		CodeRepo4: '',
		Image: '',
		Thumbnail: '',
	},
	{
		Name: 'The Legend of Lambda',
		Type: 'Team Project',
		Description: '',
		Team: '',
		TechStack1: '',
		TechStack2: '',
		TechStack3: '',
		SiteLink: '',
		PresentationVideo: '',
		MarketingVideo: '',
		CodeRepo1: '',
		CodeRepo2: '',
		CodeRepo3: '',
		CodeRepo4: '',
		Image: '',
		Thumbnail: '',
	},
	{
		Name: 'International Child Nutrition Status Tracking',
		Type: 'Team Project',
		Description: '',
		Team: '',
		TechStack1: '',
		TechStack2: '',
		TechStack3: '',
		SiteLink: '',
		PresentationVideo: '',
		MarketingVideo: '',
		CodeRepo1: '',
		CodeRepo2: '',
		CodeRepo3: '',
		CodeRepo4: '',
		Image: '',
		Thumbnail: '',
	},
	{
		Name: 'Ride for Life with Safe',
		Type: 'Team Project',
		Description: '',
		Team: '',
		TechStack1: '',
		TechStack2: '',
		TechStack3: '',
		SiteLink: '',
		PresentationVideo: '',
		MarketingVideo: '',
		CodeRepo1: '',
		CodeRepo2: '',
		CodeRepo3: '',
		CodeRepo4: '',
		Image: '',
		Thumbnail: '',
	},
	{
		Name: 'Create Your Own Adventure',
		Type: 'Team Project',
		Description: '',
		Team: '',
		TechStack1: '',
		TechStack2: '',
		TechStack3: '',
		SiteLink: '',
		PresentationVideo: '',
		MarketingVideo: '',
		CodeRepo1: '',
		CodeRepo2: '',
		CodeRepo3: '',
		CodeRepo4: '',
		Image: '',
		Thumbnail: '',
	},
	{
		Name: 'GitHired',
		Type: 'Team Project',
		Description: '',
		Team: '',
		TechStack1: '',
		TechStack2: '',
		TechStack3: '',
		SiteLink: '',
		PresentationVideo: '',
		MarketingVideo: '',
		CodeRepo1: '',
		CodeRepo2: '',
		CodeRepo3: '',
		CodeRepo4: '',
		Image: '',
		Thumbnail: '',
	},
	{
		Name: 'Find A Brewery!',
		Type: 'Team Project',
		Description: '',
		Team: '',
		TechStack1: '',
		TechStack2: '',
		TechStack3: '',
		SiteLink: '',
		PresentationVideo: '',
		MarketingVideo: '',
		CodeRepo1: '',
		CodeRepo2: '',
		CodeRepo3: '',
		CodeRepo4: '',
		Image: '',
		Thumbnail: '',
	},
];
